name: YMHA Kandy
logo: logo.png
baseurl: ""
d2: We have been serving the Kandyan society for 50 years since 1973 to preserve the art & culture, social unity, and the great purpose of the dharma of Hindus. Developing students' educational status, building a society without racial or casteist ideology, and coordinating with other religious organizations to create a strong bonding among the people in Kandy, which is a multicultural territory.
description: At YMHA Kandy, we are committed to create a vibrant and diverse society in Kandy where people of all faiths, cultures, and backgrounds can live together harmoniously. We strive to achieve this through inspiring and strengthening social unity, promoting education, embracing art and culture, and eliminating any form of racial or caste-based prejudice. By working in close collaboration with other religious organisations, we hope to foster an atmosphere of empathy and understanding, in order to make Kandy a peaceful place to live.
announcement: This is an announcement with data and time included | 25/11/2022

served_count: 2450
donate_message: Donate as much as you can for the successful service of YMHA
contribute_message: If you can help us in any other ways, please contact us.

address: No. 100, Peradeniya road, Kandy, Sri Lanka.
phone: +94 81 2204 324
email: ymhakandy@gmail.com
website: www.ymhakandy.org

collections:
  services:
    output: true
    permalink: /services/:title
  gallery:
    output: true
    permalink: /gallery/:image
  news:
    output: true
    permalink: /news/:title
